repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4 
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--exclude=alembic/"]
        exclude: ^alembic/

  - repo: local
    hooks:
      - id: run-pytest
        name: tests
        entry: bash -c 'PYTHONPATH=. pytest tests'
        language: system
        types: [python]
        pass_filenames: false