"""Add unique constraint on user_id and category

Revision ID: 0614fb4f12fa
Revises: 0e533a688f39
Create Date: 2025-07-09 15:15:26.119172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0614fb4f12fa'
down_revision: Union[str, Sequence[str], None] = '0e533a688f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_category', 'user_facts', ['user_id', 'category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_category', 'user_facts', type_='unique')
    # ### end Alembic commands ###
